### ISSUE TITLE
Cannot Generate Payload expected 'STRING', found '<<'

### ISSUE THREAD

**Issue by alex404sl** [optiv/ScareCrow#49] opened 2022-03-23 21:57 UTC
Thank you for the code and latest update, however, I could not generate exe on latest 4.0.

Raw payload generated by lastest CS

```
sudo ./ScareCrow -I ~/Downloads/beacon.bin -Loader control -domain www.microsoft.com -O test.exe
```
will gave me the following error message:

```
[*] Compiling Payload
exit status 1: go list error: exit status 1: inputs.go:8:1: expected 'STRING', found '<<'


[+] Payload Compiled
```

Each time run the command will pop a different file name, but same location, for example:

```
exit status 1: go list error: exit status 1: winsec.go:8:1: expected 'STRING', found '<<'
exit status 1: go list error: exit status 1: netfirewall.go:8:1: expected 'STRING', found '<<'
```

Thanks!!

**Comment by Tylous** [comment] 2022-03-23 22:01
ack... looks like the latest push pushed the line change indicators... will update this shortly when its fixed.

**Comment by Tylous** [comment] 2022-03-23 22:14
@alex404sl I've fixed this issue please pull down a fresh copy. I will close this shortly if the issue is addressed, please let me know if it's not.

**Comment by alex404sl** [comment] 2022-03-23 22:18
Working now, thanks!!

**Closed as completed** 2022-03-24 00:46 UTC
